CLASS ZCL_DEMO_E2E_0430100652 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS add
      IMPORTING iv_a TYPE i
                iv_b TYPE i
      RETURNING VALUE(rv_sum) TYPE i.
ENDCLASS.

CLASS ZCL_DEMO_E2E_0430100652 IMPLEMENTATION.
  METHOD add.
    " E2E_DEMO_MARKER_CLAS
    rv_sum = iv_a + iv_b.
  ENDMETHOD.
ENDCLASS.